### ISSUE TITLE
Masukan untuk sistem SIMBELMAWA DIKTI PKM

### ISSUE THREAD

**Issue by fhpraw** [fathonir/Simbelmawa.WebForm#26]
Assalamu'alaikum Warahmatullahi Wabarakatuhu
Salam Sejahtera
Yth. Bapak @fathonir  dan tim IT SIMBELMAWA

Kami dari operator PT ingin menyampaikan masukan untuk sistem SIMBELMAWA yang bapak buat:

1. Terkait dengan pembuatan akun mahasiswa, bagi PT Klaster 1 yang memiliki kuota 700, akan sangat merepotkan jika **harus menginput 700 akun mahasiswa satu persatu**. Sebaiknya ditambahkan fitur bulk action yang memungkinkan pendaftaran akun secara serentak dg hanya mengupload 700 data yang tersimpan dalam satu file CSV.
2. Terkait dengan sistem rekap, tahun lalu (2017) masih tersedia **fitur rekap data proposal seluruh tim PKM** dalam bentuk excel, akan tetapi tahun 2018 hingga sekarang, fitur rekap itu dihapus, hanya disediakan pada tim pkm yang didanai. mohon kiranya bapak bisa munculkan kembali fitur rekap seluruh tim baik yang didanai maupun yang tidak lolos didanai.
4. Mohon data rekap benar benar lengkap mulai dari data **NIM, Nama lengkap, skim, judul, NIDN Pembimbing, Nama Pembimbing, daftar anggota, nomor kontak, email, username, password.**
5. Mohon disediakan fitur download PDF proposal.
3. Terkait input data mahasiswa dan dosen pembimbing, **mohon input data cukup diambil dari NIM dan NIDN saja.** Adapun data lainnya nama lengkap, prodi, data lainnya cukup disinkronkan otomatis dengan data forlap. jadi operator PT tidak perlu input data manual lagi, supaya menghindari terjadi kesalahan input data ataupun data redundan.

Atas perhatiannya kami ucapkan terimakasih.
Wassalamu'alaikum Warahmatullahi Wabarakatuhu
Salam Sejahtera

**Comment by fathonir** [comment]
Walaikumsalam pak @fhpraw ,
Sebelumnya saya ucapkan terima kasih banyak pak atas masukkannya. 

> 1. Terkait dengan pembuatan akun mahasiswa, bagi PT Klaster 1 yang memiliki kuota 700, akan sangat merepotkan jika **harus menginput 700 akun mahasiswa satu persatu**. Sebaiknya ditambahkan fitur bulk action yang memungkinkan pendaftaran akun secara serentak dg hanya mengupload 700 data yang tersimpan dalam satu file CSV.
> 2. Terkait dengan sistem rekap, tahun lalu (2017) masih tersedia **fitur rekap data proposal seluruh tim PKM** dalam bentuk excel, akan tetapi tahun 2018 hingga sekarang, fitur rekap itu dihapus, hanya disediakan pada tim pkm yang didanai. mohon kiranya bapak bisa munculkan kembali fitur rekap seluruh tim baik yang didanai maupun yang tidak lolos didanai.
> 3. Mohon data rekap benar benar lengkap mulai dari data **NIM, Nama lengkap, skim, judul, NIDN Pembimbing, Nama Pembimbing, daftar anggota, nomor kontak, email, username, password.**

Untuk fitur-fitur ini akan usahakan kita fasilitasi segera pak, tim sedang menyiapkan ini.

> 4. Mohon disediakan fitur download PDF proposal.

Untuk fitur ini sudah tersedia di halaman bimbingan dosen dan halaman pimpinan perguruan tinggi. 

> 5. Terkait input data mahasiswa dan dosen pembimbing, **mohon input data cukup diambil dari NIM dan NIDN saja.** Adapun data lainnya nama lengkap, prodi, data lainnya cukup disinkronkan otomatis dengan data forlap. jadi operator PT tidak perlu input data manual lagi, supaya menghindari terjadi kesalahan input data ataupun data redundan.

Terkait sinkronisasi ini, proses sinkronisasi terjadi secara otomatis ketika mengentrikan judul. Tetapi untuk NIDN yang belum terdaftar untuk sementara bisa melapor dulu via email ke email kami di : subdit.penalaran.kreativitas@ristekdikti.go.id . Karena tim juga sedang bekerja untuk menyiapkan fitur sinkronisasi yang lebih mudah.
